import { createFileRoute } from "@tanstack/react-router";
import { useEffect, useState, type ReactNode } from "react";
import { AppShell } from "@/components/AppShell";
import { Card, SectionTitle } from "@/components/ui-kit";
import { getMyProfile, PROFILE_COSTUMES, PROFILE_SKILLS, updateMyProfile, type CollaboratorProfile } from "@/lib/api";
import { UserRound } from "lucide-react";

export const Route = createFileRoute("/u/profilo")({ component: ProfiloUtente });

function ProfiloUtente() {
  const [profile,setProfile]=useState<CollaboratorProfile|null>(null); const [skills,setSkills]=useState<string[]>([]); const [costumes,setCostumes]=useState<string[]>([]);
  const [email,setEmail]=useState(""); const [phone,setPhone]=useState(""); const [bio,setBio]=useState(""); const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(false); const [message,setMessage]=useState(""); const [error,setError]=useState("");
  useEffect(()=>{getMyProfile().then(r=>{setProfile(r.user);setSkills(r.user.skills||[]);setCostumes(r.user.costumeFlags||[]);setEmail(r.user.email||"");setPhone(r.user.phone||"");setBio(r.user.bio||"")}).catch(e=>setError(e instanceof Error?e.message:"Impossibile caricare il profilo")).finally(()=>setLoading(false))},[]);
  const toggle=(v:string,list:string[],set:(x:string[])=>void)=>set(list.includes(v)?list.filter(x=>x!==v):[...list,v]);
  async function save(){setSaving(true);setMessage("");setError("");try{const r=await updateMyProfile({email,phone,bio,skills,costumeFlags:costumes});setProfile(r.user);setSkills(r.user.skills||[]);setCostumes(r.user.costumeFlags||[]);setMessage("Profilo salvato")}catch(e){setError(e instanceof Error?e.message:"Impossibile salvare il profilo")}finally{setSaving(false)}}
  if(loading)return <AppShell area="u" title="" back="/u"><section className="px-3 pt-6 text-sm text-muted-foreground">Caricamento profilo…</section></AppShell>;
  if(!profile)return <AppShell area="u" title="" back="/u"><section className="px-3 pt-6 text-sm text-destructive">{error||"Profilo non disponibile"}</section></AppShell>;
  return <AppShell area="u" title="" back="/u"><section className="pt-6"><p className="eyebrow text-accent">Scheda personale</p><h2 className="mt-1 font-serif text-2xl text-primary">Il mio profilo</h2><p className="mt-1 text-sm text-muted-foreground">Le informazioni usate dall'ufficio per selezionarti per gli eventi.</p></section>
    <section className="mt-6"><SectionTitle>Dati personali</SectionTitle><Card><div className="grid gap-4"><Field label="Nome e cognome"><input disabled value={`${profile.nome} ${profile.cognome}`} className="w-full rounded-lg border border-border bg-muted px-3 py-2 text-sm text-muted-foreground"/></Field><Field label="Username"><input disabled value={profile.username} className="w-full rounded-lg border border-border bg-muted px-3 py-2 text-sm text-muted-foreground"/></Field><Field label="Telefono"><input value={phone} onChange={e=>setPhone(e.target.value)} className="w-full rounded-lg border border-border bg-surface px-3 py-2 text-sm text-foreground"/></Field><Field label="Email"><input value={email} onChange={e=>setEmail(e.target.value)} className="w-full rounded-lg border border-border bg-surface px-3 py-2 text-sm text-foreground"/></Field><Field label="Presentazione"><textarea value={bio} onChange={e=>setBio(e.target.value)} className="min-h-24 w-full rounded-lg border border-border bg-surface px-3 py-2 text-sm text-foreground"/></Field></div></Card></section>
    <FlagSection title="Competenze" values={PROFILE_SKILLS} selected={skills} toggle={v=>toggle(v,skills,setSkills)}/><FlagSection title="Costumi e dotazioni" values={PROFILE_COSTUMES} selected={costumes} toggle={v=>toggle(v,costumes,setCostumes)}/>
    <div className="mt-6"><button onClick={save} disabled={saving} className="min-h-12 w-full bg-primary px-4 text-sm font-semibold uppercase tracking-[0.08em] text-white disabled:opacity-60">{saving?"Salvataggio…":"Salva scheda personale"}</button>{message&&<p className="mt-3 text-sm text-green-700">{message}</p>}{error&&<p className="mt-3 text-sm text-destructive">{error}</p>}</div>
  </AppShell>;
}
function FlagSection({title,values,selected,toggle}:{title:string;values:readonly string[];selected:string[];toggle:(v:string)=>void}){return <section className="mt-8"><SectionTitle>{title}</SectionTitle><Card><p className="mb-3 text-sm text-muted-foreground">Spunta le voci applicabili alla tua scheda.</p><div className="grid gap-2 sm:grid-cols-2">{values.map(v=><label key={v} className="flex min-h-12 cursor-pointer items-center gap-3 rounded-lg border border-border bg-surface px-3 py-3 text-sm"><input type="checkbox" checked={selected.includes(v)} onChange={()=>toggle(v)} className="h-5 w-5 shrink-0 accent-accent"/><span className="font-medium text-foreground">{v}</span></label>)}</div></Card></section>}
function Field({label,children}:{label:string;children:ReactNode}){return <label className="block"><span className="mb-2 flex items-center gap-2 text-xs font-semibold uppercase tracking-[0.08em] text-muted-foreground"><UserRound className="h-3.5 w-3.5"/>{label}</span>{children}</label>}
