/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminArchivioRouteImport } from './routes/admin.archivio'
import { Route as AdminCalendarioRouteImport } from './routes/admin.calendario'
import { Route as AdminNotificheRouteImport } from './routes/admin.notifiche'
import { Route as AdminReportRouteImport } from './routes/admin.report'
import { Route as UIndexRouteImport } from './routes/u.index'
import { Route as UCalendarioRouteImport } from './routes/u.calendario'
import { Route as UNotificheRouteImport } from './routes/u.notifiche'
import { Route as UProfiloRouteImport } from './routes/u.profilo'
import { Route as AdminCollaboratoriIndexRouteImport } from './routes/admin.collaboratori.index'
import { Route as AdminCollaboratoriIdRouteImport } from './routes/admin.collaboratori.$id'
import { Route as AdminEventiIndexRouteImport } from './routes/admin.eventi.index'
import { Route as AdminEventiCodeRouteImport } from './routes/admin.eventi.$code'
import { Route as AdminEventiNuovoRouteImport } from './routes/admin.eventi.nuovo'
import { Route as UBollaCodeRouteImport } from './routes/u.bolla.$code'
import { Route as UEventiIndexRouteImport } from './routes/u.eventi.index'
import { Route as UEventiCodeRouteImport } from './routes/u.eventi.$code'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminArchivioRoute = AdminArchivioRouteImport.update({
  id: '/admin/archivio',
  path: '/admin/archivio',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCalendarioRoute = AdminCalendarioRouteImport.update({
  id: '/admin/calendario',
  path: '/admin/calendario',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminNotificheRoute = AdminNotificheRouteImport.update({
  id: '/admin/notifiche',
  path: '/admin/notifiche',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReportRoute = AdminReportRouteImport.update({
  id: '/admin/report',
  path: '/admin/report',
  getParentRoute: () => rootRouteImport,
} as any)
const UIndexRoute = UIndexRouteImport.update({
  id: '/u/',
  path: '/u/',
  getParentRoute: () => rootRouteImport,
} as any)
const UCalendarioRoute = UCalendarioRouteImport.update({
  id: '/u/calendario',
  path: '/u/calendario',
  getParentRoute: () => rootRouteImport,
} as any)
const UNotificheRoute = UNotificheRouteImport.update({
  id: '/u/notifiche',
  path: '/u/notifiche',
  getParentRoute: () => rootRouteImport,
} as any)
const UProfiloRoute = UProfiloRouteImport.update({
  id: '/u/profilo',
  path: '/u/profilo',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCollaboratoriIndexRoute = AdminCollaboratoriIndexRouteImport.update({
  id: '/admin/collaboratori/',
  path: '/admin/collaboratori/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCollaboratoriIdRoute = AdminCollaboratoriIdRouteImport.update({
  id: '/admin/collaboratori/$id',
  path: '/admin/collaboratori/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEventiIndexRoute = AdminEventiIndexRouteImport.update({
  id: '/admin/eventi/',
  path: '/admin/eventi/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEventiCodeRoute = AdminEventiCodeRouteImport.update({
  id: '/admin/eventi/$code',
  path: '/admin/eventi/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEventiNuovoRoute = AdminEventiNuovoRouteImport.update({
  id: '/admin/eventi/nuovo',
  path: '/admin/eventi/nuovo',
  getParentRoute: () => rootRouteImport,
} as any)
const UBollaCodeRoute = UBollaCodeRouteImport.update({
  id: '/u/bolla/$code',
  path: '/u/bolla/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const UEventiIndexRoute = UEventiIndexRouteImport.update({
  id: '/u/eventi/',
  path: '/u/eventi/',
  getParentRoute: () => rootRouteImport,
} as any)
const UEventiCodeRoute = UEventiCodeRouteImport.update({
  id: '/u/eventi/$code',
  path: '/u/eventi/$code',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin/archivio': typeof AdminArchivioRoute
  '/admin/calendario': typeof AdminCalendarioRoute
  '/admin/notifiche': typeof AdminNotificheRoute
  '/admin/report': typeof AdminReportRoute
  '/u/calendario': typeof UCalendarioRoute
  '/u/notifiche': typeof UNotificheRoute
  '/u/profilo': typeof UProfiloRoute
  '/admin/': typeof AdminIndexRoute
  '/u/': typeof UIndexRoute
  '/admin/collaboratori/$id': typeof AdminCollaboratoriIdRoute
  '/admin/eventi/$code': typeof AdminEventiCodeRoute
  '/admin/eventi/nuovo': typeof AdminEventiNuovoRoute
  '/u/bolla/$code': typeof UBollaCodeRoute
  '/u/eventi/$code': typeof UEventiCodeRoute
  '/admin/collaboratori/': typeof AdminCollaboratoriIndexRoute
  '/admin/eventi/': typeof AdminEventiIndexRoute
  '/u/eventi/': typeof UEventiIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/archivio': typeof AdminArchivioRoute
  '/admin/calendario': typeof AdminCalendarioRoute
  '/admin/notifiche': typeof AdminNotificheRoute
  '/admin/report': typeof AdminReportRoute
  '/u/calendario': typeof UCalendarioRoute
  '/u/notifiche': typeof UNotificheRoute
  '/u/profilo': typeof UProfiloRoute
  '/admin': typeof AdminIndexRoute
  '/u': typeof UIndexRoute
  '/admin/collaboratori/$id': typeof AdminCollaboratoriIdRoute
  '/admin/eventi/$code': typeof AdminEventiCodeRoute
  '/admin/eventi/nuovo': typeof AdminEventiNuovoRoute
  '/u/bolla/$code': typeof UBollaCodeRoute
  '/u/eventi/$code': typeof UEventiCodeRoute
  '/admin/collaboratori': typeof AdminCollaboratoriIndexRoute
  '/admin/eventi': typeof AdminEventiIndexRoute
  '/u/eventi': typeof UEventiIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin/archivio': typeof AdminArchivioRoute
  '/admin/calendario': typeof AdminCalendarioRoute
  '/admin/notifiche': typeof AdminNotificheRoute
  '/admin/report': typeof AdminReportRoute
  '/u/calendario': typeof UCalendarioRoute
  '/u/notifiche': typeof UNotificheRoute
  '/u/profilo': typeof UProfiloRoute
  '/admin/': typeof AdminIndexRoute
  '/u/': typeof UIndexRoute
  '/admin/collaboratori/$id': typeof AdminCollaboratoriIdRoute
  '/admin/eventi/$code': typeof AdminEventiCodeRoute
  '/admin/eventi/nuovo': typeof AdminEventiNuovoRoute
  '/u/bolla/$code': typeof UBollaCodeRoute
  '/u/eventi/$code': typeof UEventiCodeRoute
  '/admin/collaboratori/': typeof AdminCollaboratoriIndexRoute
  '/admin/eventi/': typeof AdminEventiIndexRoute
  '/u/eventi/': typeof UEventiIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin/archivio'
    | '/admin/calendario'
    | '/admin/notifiche'
    | '/admin/report'
    | '/u/calendario'
    | '/u/notifiche'
    | '/u/profilo'
    | '/admin/'
    | '/u/'
    | '/admin/collaboratori/$id'
    | '/admin/eventi/$code'
    | '/admin/eventi/nuovo'
    | '/u/bolla/$code'
    | '/u/eventi/$code'
    | '/admin/collaboratori/'
    | '/admin/eventi/'
    | '/u/eventi/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/archivio'
    | '/admin/calendario'
    | '/admin/notifiche'
    | '/admin/report'
    | '/u/calendario'
    | '/u/notifiche'
    | '/u/profilo'
    | '/admin'
    | '/u'
    | '/admin/collaboratori/$id'
    | '/admin/eventi/$code'
    | '/admin/eventi/nuovo'
    | '/u/bolla/$code'
    | '/u/eventi/$code'
    | '/admin/collaboratori'
    | '/admin/eventi'
    | '/u/eventi'
  id:
    | '__root__'
    | '/'
    | '/admin/archivio'
    | '/admin/calendario'
    | '/admin/notifiche'
    | '/admin/report'
    | '/u/calendario'
    | '/u/notifiche'
    | '/u/profilo'
    | '/admin/'
    | '/u/'
    | '/admin/collaboratori/$id'
    | '/admin/eventi/$code'
    | '/admin/eventi/nuovo'
    | '/u/bolla/$code'
    | '/u/eventi/$code'
    | '/admin/collaboratori/'
    | '/admin/eventi/'
    | '/u/eventi/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminArchivioRoute: typeof AdminArchivioRoute
  AdminCalendarioRoute: typeof AdminCalendarioRoute
  AdminNotificheRoute: typeof AdminNotificheRoute
  AdminReportRoute: typeof AdminReportRoute
  UCalendarioRoute: typeof UCalendarioRoute
  UNotificheRoute: typeof UNotificheRoute
  UProfiloRoute: typeof UProfiloRoute
  AdminIndexRoute: typeof AdminIndexRoute
  UIndexRoute: typeof UIndexRoute
  AdminCollaboratoriIdRoute: typeof AdminCollaboratoriIdRoute
  AdminEventiCodeRoute: typeof AdminEventiCodeRoute
  AdminEventiNuovoRoute: typeof AdminEventiNuovoRoute
  UBollaCodeRoute: typeof UBollaCodeRoute
  UEventiCodeRoute: typeof UEventiCodeRoute
  AdminCollaboratoriIndexRoute: typeof AdminCollaboratoriIndexRoute
  AdminEventiIndexRoute: typeof AdminEventiIndexRoute
  UEventiIndexRoute: typeof UEventiIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/archivio': {
      id: '/admin/archivio'
      path: '/admin/archivio'
      fullPath: '/admin/archivio'
      preLoaderRoute: typeof AdminArchivioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/calendario': {
      id: '/admin/calendario'
      path: '/admin/calendario'
      fullPath: '/admin/calendario'
      preLoaderRoute: typeof AdminCalendarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/notifiche': {
      id: '/admin/notifiche'
      path: '/admin/notifiche'
      fullPath: '/admin/notifiche'
      preLoaderRoute: typeof AdminNotificheRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/report': {
      id: '/admin/report'
      path: '/admin/report'
      fullPath: '/admin/report'
      preLoaderRoute: typeof AdminReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/': {
      id: '/u/'
      path: '/u'
      fullPath: '/u/'
      preLoaderRoute: typeof UIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/calendario': {
      id: '/u/calendario'
      path: '/u/calendario'
      fullPath: '/u/calendario'
      preLoaderRoute: typeof UCalendarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/notifiche': {
      id: '/u/notifiche'
      path: '/u/notifiche'
      fullPath: '/u/notifiche'
      preLoaderRoute: typeof UNotificheRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/profilo': {
      id: '/u/profilo'
      path: '/u/profilo'
      fullPath: '/u/profilo'
      preLoaderRoute: typeof UProfiloRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/collaboratori/': {
      id: '/admin/collaboratori/'
      path: '/admin/collaboratori'
      fullPath: '/admin/collaboratori/'
      preLoaderRoute: typeof AdminCollaboratoriIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/collaboratori/$id': {
      id: '/admin/collaboratori/$id'
      path: '/admin/collaboratori/$id'
      fullPath: '/admin/collaboratori/$id'
      preLoaderRoute: typeof AdminCollaboratoriIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/eventi/': {
      id: '/admin/eventi/'
      path: '/admin/eventi'
      fullPath: '/admin/eventi/'
      preLoaderRoute: typeof AdminEventiIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/eventi/$code': {
      id: '/admin/eventi/$code'
      path: '/admin/eventi/$code'
      fullPath: '/admin/eventi/$code'
      preLoaderRoute: typeof AdminEventiCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/eventi/nuovo': {
      id: '/admin/eventi/nuovo'
      path: '/admin/eventi/nuovo'
      fullPath: '/admin/eventi/nuovo'
      preLoaderRoute: typeof AdminEventiNuovoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/bolla/$code': {
      id: '/u/bolla/$code'
      path: '/u/bolla/$code'
      fullPath: '/u/bolla/$code'
      preLoaderRoute: typeof UBollaCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/eventi/': {
      id: '/u/eventi/'
      path: '/u/eventi'
      fullPath: '/u/eventi/'
      preLoaderRoute: typeof UEventiIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/eventi/$code': {
      id: '/u/eventi/$code'
      path: '/u/eventi/$code'
      fullPath: '/u/eventi/$code'
      preLoaderRoute: typeof UEventiCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminArchivioRoute: AdminArchivioRoute,
  AdminCalendarioRoute: AdminCalendarioRoute,
  AdminNotificheRoute: AdminNotificheRoute,
  AdminReportRoute: AdminReportRoute,
  UCalendarioRoute: UCalendarioRoute,
  UNotificheRoute: UNotificheRoute,
  UProfiloRoute: UProfiloRoute,
  AdminIndexRoute: AdminIndexRoute,
  UIndexRoute: UIndexRoute,
  AdminCollaboratoriIdRoute: AdminCollaboratoriIdRoute,
  AdminEventiCodeRoute: AdminEventiCodeRoute,
  AdminEventiNuovoRoute: AdminEventiNuovoRoute,
  UBollaCodeRoute: UBollaCodeRoute,
  UEventiCodeRoute: UEventiCodeRoute,
  AdminCollaboratoriIndexRoute: AdminCollaboratoriIndexRoute,
  AdminEventiIndexRoute: AdminEventiIndexRoute,
  UEventiIndexRoute: UEventiIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
